### PR TITLE
Feat/logo update

### PR DESCRIPTION
**Pull request by lentsius-bark**
updates the logo

note: 
- i left the svg and larger export white, as that allows us to modulate it to any colour with ease

### CODE REVIEW

**Comment by Structed** [comment]
Like that you left the main export and SVG white for modulation. I wouldn't have thought about that!

**Review by Structed — CHANGES_REQUESTED** [review]
We discussed updating the splash screen logo on Discord. Can you add this here, please? Thanks!

**Comment by lentsius-bark** [comment]
image
proposals! what do you think @Structed ?

**Comment by Structed** [comment]
Lovely! Do I have to decide? 😂
Both are gorgeous!

**Comment by lentsius-bark** [comment]
Splash screen added

**Comment by lentsius-bark** [comment]
rebased

**Comment by Structed** [comment]
> > Lovely! Do I have to decide? 😂
> > Both are gorgeousl!
> > The Orange one represents the PlayFab brand better, though. So I think that one. But I really want the other version to have it's use somewhere, too!
> 
> Alright! Like you say, those are the playfab colours, I'll go ahead and update the PR :) shall I put the other one in the repo as well?

yes please! Thanks

**Review by Structed — DISMISSED** [review]

**Comment by lentsius-bark** [comment]
Alright! Will do

**Comment by lentsius-bark** [comment]
@Structed added the monochrome version as well, should be ready to merge now :)

**Comment by Structed** [comment]
Awesome! This looks so great! Will merge when at a PC.

**Pull request merged**
